### ISSUE TITLE
GNU General Public License or Copyright?

### ISSUE THREAD

**Issue by Perfectdotexe** [reginildo/Tomato#11]
I noticed that you have Copyright and GNU General Public License for the project? Forked and pushed a small fix. Still learning how to use GitHub, apologies for any mistakes updating this should've been custom issue template.

**Comment by Perfectdotexe** [comment]
("GNU General Public License v3.0 2019", JLabel.CENTER); should be correct licensing, didn't know that there were various versions.

**Comment by gnormor** [comment]
Thank you for your help =) @Perfectdotexe
